// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://budetkkzijqzomcptxcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZGV0a2t6aWpxem9tY3B0eGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTY2MzUsImV4cCI6MjA2NTUzMjYzNX0.xWsvV4f6MdxSVrj_jaTLZabWwt7zpietoIvse6P883o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);